server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/ukgdemo2?allowPublicKeyRetrieval=true&useSSL=false
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

